name: PullSheets

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  update_sheets:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Lmao1
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      
      - name: Run Script
        run: |
          python3 ./scripts/google-sheets.py
    
      - name: Push to repository
        run: |
          git add .
          git commit -m "AutoCommit: updating sheets"
          git push
